<?php

/**
 * @file
 * D2D Search module.
 */

require_once 'includes/qscience_d2dsearch.form.inc';
require_once 'includes/qscience_d2dsearch.papers.inc';

/**
 * Implements hook_menu_alter().
 */
function qscience_d2dsearch_menu() {
  $items['qscience_search'] = array(
    'title' => 'QScience Search',
    'page callback' => 'qscience_d2dsearch_main',
    'access arguments' => array('use qscience search'),
    'type' => MENU_LOCAL_TASK,
    'weight' => 80,
  );
  $items['qscience_search/get_result'] = array(
    'page callback' => 'qscience_d2dsearch_get_results',
    'access arguments' => array('use qscience search'),
    'type' => MENU_CALLBACK,
  );
   $item['qscience_search/import_paper'] = array(
     'page callback' => '_qscience_d2dsearch_import_paper',
     'access arguments' => array('use qscience search'),
   );
  return $items;
}

/**
 * Implements hook_permission().
 */
function qscience_d2dsearch_permission() {
  return array(
    'use qscience search' => array(
      'title' => t('Use QScience D2D search'),
    ),
  );
}

/**
 * Implements hook_d2dsearch_query_type().
 */
function qscience_d2dsearch_d2dsearch_query_type() {
  $types = array();
  $types['qscience_d2dsearch_papers'] = array(
    'callback' => '_qscience_d2dsearch_papers_callback',
  );

  return $types;
}


